add

diff --git a/.github/workflows/docs-keywords-filter.yml b/.github/workflows/docs-keywords-filter.yml
--- a/.github/workflows/docs-keywords-filter.yml
+++ b/.github/workflows/docs-keywords-filter.yml
@@ -6,6 +6,7 @@ on:
     branches:
       - master
       - release-*
+      - filter-*
   pull_request:
     branches:
       - master
@@ -24,6 +25,11 @@ jobs:
     name: docs-keywords-filter
     runs-on: ubuntu-20.04
     steps:
+      - name: Dump GitHub context
+        env:
+          GITHUB_CONTEXT: ${{ toJson(github) }}
+        run: echo "$GITHUB_CONTEXT"
+        
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
@@ -41,9 +47,9 @@ jobs:
         env:
           ALL_CHANGED_DOCS: ${{ steps.changed-docs.outputs.all_changed_files }}
           # Keywords regex for grep
-          GREP_KEYWORD_DICS: 'you\|they'
+          GREP_KEYWORD_DICS: 'you\|yours\|they\|them\|their'
           # Error tips
-          TIPS: 'In the docs we try not to use (you,they),please check the file(s) below:'
+          TIPS: 'In the docs we try not to use (you,yours,they,them,their)'
         run: |
 
           echo -e "Changed files: \n ${ALL_CHANGED_DOCS}"
@@ -52,17 +58,22 @@ jobs:
           if [[ "${{ github.event_name }}" == "pull_request" ]];then
              base_sha=${{ github.event.pull_request.base.sha }}
              head_sha=${{ github.event.pull_request.head.sha }}
-          else
+          elif [[ "${{ github.event_name }}" == "push" ]];then
             base_sha=${{ github.event.before }}
             head_sha=${{ github.event.after }}
           fi
           echo "Base SHA:${base_sha}"
           echo "Head SHA:${head_sha}"
 
-          error_msg=''
+          if [[ "${base_sha}" == "" || "head_sha" == "" ]];then
+            echo "base sha or head sha is empty, event : ${{ github.event_name }} "
+            exit 1
+          fi
+
           # Grep may return 1 when no added content
           set +e
 
+          echo "${TIPS}"
           for file in ${ALL_CHANGED_DOCS}; do
             # Get changed content by 'git diff'
             # Delete diff summary by sed
@@ -70,15 +81,17 @@ jobs:
             # Match keywords as words and ignore case
             content_with_keyword="$(git diff ${base_sha} ${head_sha} ${file}|sed '0,/^@/d'|grep '^+'|grep -iw ${GREP_KEYWORD_DICS})"
             if [[ "x${content_with_keyword}" != "x" ]] ; then
-              error_msg="${error_msg}${file}\n${content_with_keyword}\n\n"
+              echo "❌ Failed : ${file}"
+              echo "${content_with_keyword}"
+            else
+              echo "✅ Success : ${file}"
             fi
           done
 
-          if [[ "x${error_msg}" != "x" ]]; then
-             echo "Check failed"
-             echo -e "${TIPS}\n${error_msg}"
-             exit 1
+          # exit with error if keywords matched
+          if [[ "x${content_with_keyword}" != "x" ]]; then
+            exit 1
           else
-             echo "All check passed"
+             echo "⭐ All file passed"
              exit 0
           fi
